### ISSUE TITLE
[question] django-civil transition

### ISSUE THREAD

**Issue by petrklus** [kunitoki/nublas#4]
Hi guys and gals!

I was curious, is there any road-map of transitioning from django-civil to this new package? I've looked around nublas but could not find much in terms of documentation / other notes.

Thanks!

**Comment by kunitoki** [comment]
Actually django-civil is actually not developed anymore, but some concepts from it are already inside nublas.

Documentation, notes, unit testing in nublas is a TODO, but since i'm alone on this project i need some help for sure.
