### ISSUE TITLE
field_size

### ISSUE THREAD

**Issue by nordbit** [kunitoki/nublas#5]
```
col-sm-{{ field_size|default:10 }}
```

I have a situation with this part of template. This value "field_size" in clean envronment is displayed correctly (field_size = 2) in "Contact" , but im  my production with same python and django versions but with installed many other modules (eggs) is displayed differently (field_size = 1).
I can't find where this value is stored or calculated.

**Comment by kunitoki** [comment]
this is setup in django-formaldehyde. maybe there is some other django app that defines this ?

**Comment by nordbit** [comment]
Ok, i putted necessary value in settings.py and now is fixed.
